# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theonsapp', '0004_auto_20160310_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads'),
        ),
    ]
