# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theonsapp', '0005_auto_20160310_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/categories'),
        ),
    ]
