# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theonsapp', '0007_subcategory_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
