# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theonsapp', '0009_auto_20160503_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/categories'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='photo',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/subcategories'),
        ),
    ]
